parameters:
    itkg_consumer.type.service_config.class: Itkg\ConsumerBundle\Form\Type\ServiceConfigType
    itkg_consumer.type.client_config.class: Itkg\ConsumerBundle\Form\Type\ClientConfigType

services:
    itkg_consumer.type.service_config:
        class: %itkg_consumer.type.service_config.class%
        tags:
            - { name: form.type, alias: service_config }
    itkg_consumer.type.client_config:
        class: %itkg_consumer.type.client_config.class%
        tags:
            - { name: form.type, alias: client_config }
